repos:
-   repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
    - id: pylint
      stages: [commit]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      stages: [commit]
